name: Package App
on: [push]
jobs:
  Package-Electron-App:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Npm CI
      run: |
        npm ci
        
    - name: Build renderer
      run: |
        npm run build-renderer
        
    - name: Build electron
      run: |
        npm run build-electron
        
    - name: Copy electron bundle
      shell: pwsh
      run: |
        Copy-Item "./electron/electron-bundle.js" -Destination "build"
        Copy-Item "./electron/preload.js" -Destination "build"
        
    - name: Package electron
      run: |
        npx electron-builder build -c.extraMetadata.main=build/electron/electron-bundle.js --publish never
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: Setup
        # A file, directory or wildcard pattern that describes what to upload
        path: /dist/MuffinTube 3 Setup 3.0.0.exe
        # The desired behavior if no files are found using the provided path.
