name: Package App
on: [push]
jobs:
  Package-Electron-App:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Build capacitor plugin
      run: |
        cd capacitor-plugin-api
        npm ci
        npm run build
        cd ..
        
    - name: Npm CI Renderer
      run: |
        npm ci
        
    - name: Build renderer
      run: |
        set CI=false
        set process.env.CI=false
        npm run build-renderer

    - name: Build Android Capacitor app
      run: |
        npx cap copy android
        npx cap build android --androidreleasetype APK --keystorepath app/my-upload-key.keystore --keystorepass ${{ secrets.SIGNING_STORE_PASSWORD }} --keystorealias ${{ secrets.SIGNING_KEY_ALIAS }} --keystorealiaspass ${{ secrets.SIGNING_KEY_PASSWORD }}
        
    - name: Build electron
      run: |
        npm run build-electron
        
    - name: Copy electron bundle
      shell: pwsh
      run: |
        New-Item -Path "./build" -Name "electron" -ItemType "Directory"
        Copy-Item "./electron/electron-bundle.js" -Destination "build/electron/electron-bundle.js"
        Copy-Item "./electron/preload.js" -Destination "build/electron/preload.js"

    - name: Electron Builder Action
      # You may pin to the exact commit or the version.
      # uses: samuelmeuli/action-electron-builder@92327c67bc45ff7c38bf55d8aa8c4d75b7ea38e7
      uses: samuelmeuli/action-electron-builder@v1.6.0
      with:
        # GitHub authentication token
        github_token: ${{ secrets.github_token }}
        # Whether the app should be released after a successful build
        release: false
        # Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
        args: -c.extraMetadata.main=build/electron/electron-bundle.js

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: Setup
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/MuffinTube 3 Setup 3.0.0.exe
        # The desired behavior if no files are found using the provided path.
